defaultPlatforms:
  - linux/arm64

builds:
  - id: firewall
    dir: ./cmd/firewall
    main: .
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w
      - -X main.ldVersion={{.Git.Tag}}
      - -X main.ldCommit={{.Git.ShortCommit}}
      - -X main.ldBuildTime={{.Git.CommitDate}}
