apiVersion: ko.build/v1alpha1
kind: Ko

builds:
  - id: firewall
    dir: ./cmd/firewall
    main: .
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s
      - -w
      - -X
      - main.ldVersion={{.Env.VERSION}}
      - -X
      - main.ldCommit={{.Env.COMMIT}}
      - -X
      - main.ldBuildTime={{.Env.BUILD_TIME}}

images:
  - image: dependency-firewall
    build: firewall
    tags:
      - latest
      - '{{.Env.VERSION}}'
