package ingestgrpc

import wire "github.com/danielterry/dependency-firewall/internal/wire/ingestgrpc"

type RecordDecisionRequest = wire.RecordDecisionRequest
type RecordDecisionResponse = wire.RecordDecisionResponse
type GetDecisionByArtifactRequest = wire.GetDecisionByArtifactRequest
type GetDecisionByArtifactResponse = wire.GetDecisionByArtifactResponse
type ListDecisionsByTenantRequest = wire.ListDecisionsByTenantRequest
type ListDecisionsByTenantResponse = wire.ListDecisionsByTenantResponse
type HasRecentAllowRequest = wire.HasRecentAllowRequest
type HasRecentAllowResponse = wire.HasRecentAllowResponse
type RecordAuditEventRequest = wire.RecordAuditEventRequest
type RecordAuditEventResponse = wire.RecordAuditEventResponse
type EnqueueDependencyGraphResolveRequest = wire.EnqueueDependencyGraphResolveRequest
type EnqueueDependencyGraphResolveResponse = wire.EnqueueDependencyGraphResolveResponse
type ClaimDependencyGraphResolveRequest = wire.ClaimDependencyGraphResolveRequest
type ClaimDependencyGraphResolveResponse = wire.ClaimDependencyGraphResolveResponse
type CompleteDependencyGraphResolveRequest = wire.CompleteDependencyGraphResolveRequest
type CompleteDependencyGraphResolveResponse = wire.CompleteDependencyGraphResolveResponse
type FailDependencyGraphResolveRequest = wire.FailDependencyGraphResolveRequest
type FailDependencyGraphResolveResponse = wire.FailDependencyGraphResolveResponse
type LookupDependencyGraphContextRequest = wire.LookupDependencyGraphContextRequest
type LookupDependencyGraphContextResponse = wire.LookupDependencyGraphContextResponse
type WatchDependencyGraphResolveRequest = wire.WatchDependencyGraphResolveRequest
type DependencyGraphResolveQueuedEvent = wire.DependencyGraphResolveQueuedEvent
type Decision = wire.Decision
type EvaluationReason = wire.EvaluationReason
type ArtifactIdentity = wire.ArtifactIdentity
type Upstream = wire.Upstream
type AuditEvent = wire.AuditEvent
