package domain

import "errors"

// Sentinel errors shared across the core so that delivery adapters can map a failure to a protocol status and
// infrastructure can signal well-known conditions without leaking driver-specific error types. Compare them with
// errors.Is; the wrapped messages are safe to surface to callers.
var (
	ErrTenantNotFound                 = errors.New("tenant not found")
	ErrTenantNameConflict             = errors.New("tenant name already exists")
	ErrTenantIdentityLinkNotFound     = errors.New("tenant identity link not found")
	ErrTenantIdentityLinkConflict     = errors.New("external account is already linked")
	ErrPrincipalNotFound              = errors.New("principal not found")
	ErrPrincipalIdentityConflict      = errors.New("external subject is already linked")
	ErrOrganizationNotFound           = errors.New("organization not found")
	ErrOrganizationNameConflict       = errors.New("organization name already exists")
	ErrOrganizationMembershipNotFound = errors.New("organization membership not found")
	ErrTeamNotFound                   = errors.New("team not found")
	ErrTeamNameConflict               = errors.New("team name already exists")
	ErrTeamMembershipNotFound         = errors.New("team membership not found")
	ErrPolicyNotFound                 = errors.New("policy not found")
	ErrPolicyNameConflict             = errors.New("policy name already exists")
	ErrPolicyVersionNotFound          = errors.New("policy version not found")
	ErrPolicyDeleteEnabled            = errors.New("enabled policy cannot be deleted")
	ErrPolicyInUse                    = errors.New("policy is in use")
	ErrDeprecatedPolicyConfig         = errors.New("deprecated stored policy config")
	ErrUnsupportedPolicySchemaVersion = errors.New("unsupported policy schema version")
	ErrInvalidPolicy                  = errors.New("invalid policy")
	ErrPolicyViolation                = errors.New("policy violation")
	ErrPolicyUpstreamIncompatible     = errors.New("policy is not supported by upstream")
	ErrUpstreamNotFound               = errors.New("upstream not found")
	ErrUpstreamNameConflict           = errors.New("upstream name already exists")
	ErrUpstreamRegistryConflict       = errors.New("upstream registry already exists")
	ErrUpstreamInUse                  = errors.New("upstream is in use")
	ErrUnsupportedUpstreamCapability  = errors.New("unsupported upstream capability")
	ErrUpstreamPolicyConflict         = errors.New("upstream update conflicts with scoped policies")
	ErrUpstreamAuthInvalid            = errors.New("invalid upstream auth")
	ErrUpstreamAuthKeyUnavailable     = errors.New("upstream auth encryption key unavailable")
	ErrUpstreamAuthTransportInsecure  = errors.New("upstream auth requires secure bundle transport")
	ErrUpstreamAmbiguous              = errors.New("multiple visible upstreams require an explicit selection")
	ErrUpstreamUnavailable            = errors.New("upstream unavailable")
	ErrInvalidResourceScope           = errors.New("invalid resource scope")
	ErrEnrichmentFailed               = errors.New("enrichment failed")
	ErrAuditUnavailable               = errors.New("audit logging unavailable")
	ErrBundleUnavailable              = errors.New("bundle unavailable")
	ErrArtifactNotFound               = errors.New("artifact not found")
	ErrInvalidArtifactRef             = errors.New("invalid artifact reference")
	ErrCacheMiss                      = errors.New("cache miss")
	ErrUnauthorized                   = errors.New("unauthorized")
	ErrAuthenticationInvalid          = errors.New("authentication invalid")
	ErrActiveAccountRequired          = errors.New("active account required")
	ErrUnsupportedTenantRole          = errors.New("unsupported tenant role")
	ErrSessionBootstrapRequired       = errors.New("session bootstrap required")
	ErrSessionBootstrapConflict       = errors.New("session bootstrap conflict")
	ErrMembershipCheckUnavailable     = errors.New("tenant membership verification unavailable")
)
