package domain

import "errors"

var (
	ErrTenantNotFound                 = errors.New("tenant not found")
	ErrTenantNameConflict             = errors.New("tenant name already exists")
	ErrPolicyNotFound                 = errors.New("policy not found")
	ErrPolicyNameConflict             = errors.New("policy name already exists")
	ErrPolicyVersionNotFound          = errors.New("policy version not found")
	ErrPolicyDeleteEnabled            = errors.New("enabled policy cannot be deleted")
	ErrPolicyInUse                    = errors.New("policy is in use")
	ErrDeprecatedPolicyConfig         = errors.New("deprecated stored policy config")
	ErrUnsupportedPolicySchemaVersion = errors.New("unsupported policy schema version")
	ErrInvalidPolicy                  = errors.New("invalid policy")
	ErrPolicyViolation                = errors.New("policy violation")
	ErrPolicyUpstreamIncompatible     = errors.New("policy is not supported by upstream")
	ErrUpstreamNotFound               = errors.New("upstream not found")
	ErrUpstreamNameConflict           = errors.New("upstream name already exists")
	ErrUpstreamRegistryConflict       = errors.New("upstream registry already exists")
	ErrUpstreamInUse                  = errors.New("upstream is in use")
	ErrUnsupportedUpstreamCapability  = errors.New("unsupported upstream capability")
	ErrUpstreamPolicyConflict         = errors.New("upstream update conflicts with scoped policies")
	ErrUpstreamUnavailable            = errors.New("upstream unavailable")
	ErrEnrichmentFailed               = errors.New("enrichment failed")
	ErrArtifactNotFound               = errors.New("artifact not found")
	ErrInvalidArtifactRef             = errors.New("invalid artifact reference")
	ErrCacheMiss                      = errors.New("cache miss")
	ErrUnauthorized                   = errors.New("unauthorized")
)
